version: "2.4"
services:
  arozos:
    build: .
    volumes:
      - /app/files
      - /app/system
      - /app/web/SystemAO/vendor
      # - your/host/folder:/mount/point/in/arozos
    ports:
      - "8080:8080"
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
